### ISSUE TITLE
Expose ignoreHTTPSErrors browser configuration (cert errors, self-signed SSL - Connection is not private)

### ISSUE THREAD

**Issue by godchaser** [qahive/robotframework-puppeteer#102]
When testing in local development web pages with self-signed certificates we cannot pass through the browser error/warning dialog (Connection is not private).
We need puppeteer launch configuration option ignoreHTTPSErrors set to True to bypass this. 
Unfortunately this is not exposed through the library, but currently I have to manually expand the puppeteer_context.py file to achieve this. Please add this to configuration options. Thanks.

**Comment by atthaboon** [comment]
Hi @godchaser  noted with thanks.

**Comment by godchaser** [comment]
I tried, test cannot be run. Some variables cannot be resolved. 
Error: Variable '${DEFAULT_BROWSER}' not found.
But I agree that maybe it would be good to pass all configuration parameters to the lib itself.

To me it currently works if I expand explicitly library file (puppeteer_context.py):

        self.browser = await launch(
            headless=merged_options['headless'],
            slowMo=merged_options['slowMo'],
            devtools=merged_options['devtools'],
            defaultViewport={
                'width': merged_options['width'],
                'height': merged_options['height']
            },
            **ignoreHTTPSErrors=True,**
            args=default_args)

You can test yourself with online web pages that have some certificate issues, such as:
https://badssl.com/
https://self-signed.badssl.com/

**Comment by atthaboon** [comment]
Thanks a lot for your info. Already found the root cause. 
I'm currently looking for the proper solution to support all possible browser options.
