### ISSUE TITLE
Support visual testing

### ISSUE THREAD

**Issue by atthaboon** [qahive/robotframework-puppeteer#15]
percy:
https://docs.percy.io/docs/puppeteer
Supported (https://github.com/qahive/robotframework-puppeteer-percy)

robot eyes:
https://github.com/jz-jess/RobotEyes

**Comment by idxn** [comment]
It would be good if you implement this as well.
https://github.com/jz-jess/RobotEyes

**Comment by atthaboon** [comment]
@idxn Thanks a lot these can be one option for visual testing.

**Comment by atthaboon** [comment]
Add support Visual Testing use Percy.io with following library
https://github.com/qahive/robotframework-puppeteer-percy
