### ISSUE TITLE
Wait for Alert to Fully Show only Handle Alert

### ISSUE THREAD

**Issue by sss2sssss** [qahive/robotframework-puppeteer#172]
**Is your feature request related to a problem? Please describe.**
When I tried to do some sample test cases for some of my company legacy site, for some reason when I triggered one element and tried to sleep for few seconds then Handle Alert to Accept, it seems doesn't delay but proceed directly

**Describe the solution you'd like**
Wish to have a hold ability can let the alert to fully show up then only handle the button action

**Describe alternatives you've considered**
Or at least to have some delay function or async to wait the alert animation finish then only handle alert action

**Additional context**

**Comment by atthaboon** [comment]
@sss2sssss 
Want to confirm first, Alert that you mention is a Browser alert?
![image](https://user-images.githubusercontent.com/855604/184276202-888718fc-21c7-4f18-9f80-7d1822166585.png)

**Comment by sss2sssss** [comment]
> @sss2sssss Want to confirm first, Alert that you mention is a Browser alert? ![image](https://user-images.githubusercontent.com/855604/184276202-888718fc-21c7-4f18-9f80-7d1822166585.png)

Yeap is the browser alert

**Comment by atthaboon** [comment]
For bowser alert. The library will not wait but need to handle with async function.

Demo

https://github.com/qahive/robotframework-puppeteer/blob/master/Examples/alert-handler/alert-handler.robot

**Comment by atthaboon** [comment]
I will close the due to no further feedback.
Please feel free to reopen.
