### ISSUE TITLE
Request for complex file upload support

### ISSUE THREAD

**Issue by sss2sssss** [qahive/robotframework-puppeteer#177]
**Is your feature request related to a problem? Please describe.**
Currently we faced some issue for custom made multiple file upload interface where the file input is hidden
![image](https://user-images.githubusercontent.com/13049629/188590154-c7405759-bb6b-498e-bc9e-b769057f0640.png)
![image](https://user-images.githubusercontent.com/13049629/188590243-cb87f8f1-b3d8-4280-9680-6a6a6be5bd2d.png)
The "Upload File" keyword will not working on this condition (if we try to use external layer it will show Error: Node is not an HTMLInputElement; if we targeting on the file input it will waiting the field to visible until timeout)

**Describe the solution you'd like**
I think we need to have some sort of complex file upload mechanism (maybe add option on "Upload File" keyword)

**Describe alternatives you've considered**
Or maybe completely different keyword on this

**Additional context**
Refer to the screenshot attached above

**Comment by atthaboon** [comment]
Fix under v3.1.10
